name: TekZip
description: 一个码农的博客
meta_description: "关注软件开发，网站后端技术"

markdown: redcarpet
highlighter: true
logo: false
paginate: 15
baseurl: /

# Details for the RSS feed generator
url:            'ayang.github.io'
author:         'Bruce Yang'
